const $=id=>document.getElementById(id);
const screens=['home','generator','ia','consultor','leis','checklist','salvos','config'];
const occs=['Abordagem policial','Ameaça','Injúria','Difamação','Calúnia','Lesão corporal','Vias de fato','Rixa','Violência doméstica','Descumprimento de medida protetiva','Furto','Furto arrombamento','Roubo','Roubo a pedestre','Roubo de veículo','Dano','Perturbação do sossego','Desacato','Desobediência','Resistência','Tráfico de drogas','Posse de drogas','Porte ilegal de arma','Posse irregular de arma','Disparo de arma de fogo','Homicídio','Tentativa de homicídio','Feminicídio','Encontro de cadáver','Suicida/tentativa','Acidente de trânsito com dano','Acidente com lesão','Embriaguez ao volante','Direção sem CNH','Veículo recuperado','Mandado de prisão','Foragido capturado','Pessoa desaparecida','Pessoa perdida','Criança/adolescente','Maus-tratos a animais','Animal em via pública','Apoio ao SAMU','Emergência em saúde mental','Barreira policial','Cerco policial','Saturação de área','Averiguação de suspeito','Objeto encontrado','Objeto recuperado','Jogos de azar','Exercício ilegal de profissão','Violação de domicílio','Perseguição/stalking','Agressor ativo','Ocorrência em evento religioso','Ocorrência escolar','Roubo/furto a estabelecimento financeiro','Sequestro relâmpago','Alarme bancário','Estrangeiro/veículo estrangeiro','Flanelinha','Violação direito autoral'];
const laws=[
{t:'Código Penal - art. 129',k:'lesão corporal agressão',d:'Ofender a integridade corporal ou a saúde de outrem. Verificar representação, lesões aparentes, exame de corpo de delito e circunstâncias qualificadoras.'},
{t:'Código Penal - art. 147',k:'ameaça',d:'Ameaçar alguém, por palavra, escrito, gesto ou qualquer meio simbólico, de causar-lhe mal injusto e grave.'},
{t:'Código Penal - art. 147-A',k:'perseguição stalking',d:'Perseguir alguém, reiteradamente e por qualquer meio, ameaçando integridade física ou psicológica, restringindo locomoção ou invadindo privacidade.'},
{t:'Código Penal - art. 155',k:'furto',d:'Subtrair, para si ou para outrem, coisa alheia móvel. Registrar rompimento, escalada, concurso de pessoas, repouso noturno e objetos.'},
{t:'Código Penal - art. 157',k:'roubo',d:'Subtração mediante grave ameaça ou violência. Registrar arma, simulacro, lesões, número de autores, sentido da fuga e objetos.'},
{t:'Código Penal - art. 163',k:'dano',d:'Destruir, inutilizar ou deteriorar coisa alheia. Verificar representação e auto/fotos de constatação.'},
{t:'Código Penal - art. 330',k:'desobediência ordem legal',d:'Desobedecer a ordem legal de funcionário público. Descrever ordem clara, legal e possibilidade de cumprimento.'},
{t:'Código Penal - art. 331',k:'desacato ofensa policial',d:'Desacatar funcionário público no exercício da função ou em razão dela. Descrever palavras/gestos de forma objetiva.'},
{t:'LCP - art. 21',k:'vias de fato briga sem lesão',d:'Vias de fato. Quando há agressão sem lesão corporal aparente, conforme avaliação do caso.'},
{t:'LCP - art. 42',k:'perturbação sossego trabalho alheio som alto',d:'Perturbar alguém o trabalho ou o sossego alheios. Registrar horário, local, vítimas/testemunhas e cessação da perturbação.'},
{t:'Lei 11.343/06 - art. 28',k:'posse drogas consumo pessoal',d:'Porte de drogas para consumo pessoal. Registrar quantidade, acondicionamento, local e declaração do abordado.'},
{t:'Lei 11.343/06 - art. 33',k:'tráfico drogas entorpecente',d:'Tráfico de drogas. Registrar quantidade, fracionamento, dinheiro, balança, local, denúncias, atitude e demais indícios.'},
{t:'Estatuto do Desarmamento - art. 14',k:'porte ilegal arma fogo',d:'Porte ilegal de arma de fogo de uso permitido. Registrar tipo, calibre, numeração, munições e circunstâncias da localização.'},
{t:'Estatuto do Desarmamento - art. 12',k:'posse irregular arma fogo residência',d:'Posse irregular de arma de fogo de uso permitido em residência/local de trabalho.'},
{t:'Lei Maria da Penha',k:'violência doméstica mulher medida protetiva',d:'Aplicável em violência doméstica e familiar contra a mulher. Registrar relação, risco, filhos, medida protetiva, lesões e desejo da vítima.'},
{t:'Lei 13.869/19',k:'abuso autoridade cautela',d:'Lei de Abuso de Autoridade. Usar como alerta para legalidade, proporcionalidade, fundamentação e registro das medidas.'},
{t:'Súmula Vinculante 11 STF',k:'algemas algemação',d:'Uso de algemas somente em caso de resistência, fundado receio de fuga ou perigo à integridade física própria ou alheia, com justificativa escrita.'},
{t:'CTB - art. 306',k:'embriaguez direção álcool volante',d:'Conduzir veículo com capacidade psicomotora alterada. Registrar sinais, teste, recusa, auto de constatação, CNH e veículo.'},
{t:'CTB - art. 309',k:'sem habilitação cnh perigo dano',d:'Dirigir sem permissão ou habilitação gerando perigo de dano.'},
{t:'CPP - arts. 240 e 244',k:'busca pessoal fundada suspeita',d:'Busca pessoal com fundada suspeita ou mandado. Registrar a motivação concreta da suspeita.'}
];
const checklistBase=['Comunicação à sala de operações/COPOM','Segurança da guarnição e controle do local','Identificação das partes envolvidas','Consulta nos sistemas disponíveis','Fundada suspeita descrita quando houver busca pessoal','Direitos constitucionais informados quando houver prisão','Uso de algemas justificado se empregado','Vítimas/testemunhas qualificadas','Fotos/anexos/provas preservadas','Objetos apreendidos descritos e acondicionados','Condução ao atendimento médico/exame quando necessário','Apresentação na DP/DPPA ou encerramento resolvido no local','Histórico em ordem cronológica e impessoal'];
let step=0, answers={};
function init(){occs.forEach(o=>{occType.add(new Option(o,o)); checkType.add(new Option(o,o));}); $('geminiKey').value=localStorage.geminiKey||'';$('geminiKey2').value=localStorage.geminiKey||''; renderStep(); renderLaws(); renderChecklist(); renderSalvos(); if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');}
function show(id){screens.forEach(s=>$(s).classList.toggle('hidden',s!==id)); $('pageTitle').textContent=id==='home'?'COPILOTO OPERACIONAL PMRS':id.toUpperCase(); $('pageSub').textContent=id==='home'?'Tela inicial':'Módulo operacional'; document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));}
function goHome(){show('home')} function toggleFull(){document.documentElement.requestFullscreen?.()}
function renderStep(){const qs=['Data e hora do fato/atendimento','Município, bairro e endereço','Como a guarnição tomou conhecimento?','Motivo da abordagem/fundada suspeita ou solicitação','Nome/qualificação resumida das partes','O que foi constatado no local?','Houve prisão/condução? Direitos informados?','Houve uso de algemas? Justificativa?','Objetos, armas, drogas, veículos ou documentos apreendidos','Providências adotadas e destino final']; $('prog').style.width=((step+1)/qs.length*100)+'%'; $('stepBox').innerHTML=`<div class="card"><b>${step+1}/10 — ${qs[step]}</b><textarea id="stepInput" placeholder="Digite aqui...">${answers[step]||''}</textarea></div>`;}
function nextStep(){answers[step]=$('stepInput').value; if(step<9){step++;renderStep()}else generateOffline()}
function prevStep(){answers[step]=$('stepInput').value; if(step>0){step--;renderStep()}}
function generateOffline(){const tipo=$('occType').value; const txt=`Durante atendimento de ocorrência de ${tipo}, na data/hora ${answers[0]||'[informar]'}, no endereço ${answers[1]||'[informar]'}, a guarnição tomou conhecimento dos fatos por ${answers[2]||'[informar]'}.

No local, ${answers[3]||'foi verificada a situação apresentada'}, envolvendo ${answers[4]||'as partes qualificadas no boletim'}. Constatou-se que ${answers[5]||'os fatos narrados demandavam providências policiais'}.

Diante da situação, ${answers[6]||'foram adotadas as providências cabíveis'}. ${answers[7]?'Quanto ao uso de algemas: '+answers[7]+'.':''} ${answers[8]?'Foram apreendidos/relacionados: '+answers[8]+'.':''}

Por fim, ${answers[9]||'a ocorrência foi encaminhada/encerrada conforme providências legais cabíveis'}, ficando o presente registro para os devidos fins.`; $('iaOutput').textContent=txt; saveHist(tipo,txt); show('ia');}
function saveKey(){localStorage.geminiKey=$('geminiKey').value.trim(); alert('Chave salva neste aparelho.')} function saveKey2(){localStorage.geminiKey=$('geminiKey2').value.trim(); $('geminiKey').value=localStorage.geminiKey; alert('Chave salva.')}
async function callGemini(prompt){const key=(localStorage.geminiKey||$('geminiKey').value||'').trim(); if(!key) throw new Error('Informe a chave API do Gemini nas configurações.'); const model=($('geminiModel')?.value||'gemini-1.5-flash').trim(); const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`; const body={contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.25,maxOutputTokens:2200}}; const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const data=await r.json(); if(!r.ok) throw new Error(data?.error?.message||'Erro na consulta Gemini'); return data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('\n').trim()||'Sem resposta textual.';}
async function askGeminiHistory(){const input=$('iaInput').value.trim(); if(!input)return alert('Digite o relato da ocorrência.'); $('iaOutput').textContent='Consultando IA...'; const p=`Você é assistente de apoio à redação policial da Brigada Militar do Rio Grande do Sul. Gere APENAS um histórico operacional pronto para colar em BA/BO. Linguagem impessoal, técnica, cronológica e objetiva. Não escreva análise, checklist, markdown, títulos longos ou JSON. Se faltarem dados essenciais, liste no máximo 5 perguntas objetivas antes do histórico. Relato: ${input}`; try{const txt=await callGemini(p); $('iaOutput').textContent=txt; saveHist('IA Gemini',txt)}catch(e){$('iaOutput').textContent='Não foi possível consultar a IA. Motivo: '+e.message}}
async function askConsultor(mode){const q=$('consultInput').value.trim(); if(!q)return alert('Digite sua dúvida.'); addBubble(q,'user'); $('consultInput').value=''; const prefix=mode==='checklist'?'Monte um checklist operacional objetivo.':mode==='leis'?'Indique bases legais possíveis, com cautela e sem afirmar capitulação definitiva.':'Oriente operacionalmente com base na legislação brasileira, POP policial e cautelas de segurança jurídica.'; const prompt=`Você é um Consultor Policial IA para apoio a policial militar do RS. Responda em português do Brasil. ${prefix} Estruture em: orientação prática, base legal possível, providências, cautelas e modelo de texto se cabível. Não substitua autoridade policial/judiciária. Dúvida: ${q}`; addBubble('Consultando IA...','ai'); try{const txt=await callGemini(prompt); document.querySelector('#chat .ai:last-child').textContent=txt}catch(e){document.querySelector('#chat .ai:last-child').textContent='Erro: '+e.message}}
function addBubble(t,c){const d=document.createElement('div');d.className='bubble '+c;d.textContent=t;$('chat').appendChild(d);d.scrollIntoView()}
function clearChat(){$('chat').innerHTML=''}
function renderLaws(){const s=($('lawSearch').value||'').toLowerCase(); $('lawList').innerHTML=laws.filter(l=>(l.t+l.k+l.d).toLowerCase().includes(s)).map(l=>`<div class="item"><b>${l.t}</b><p class="muted">${l.d}</p><span class="pill">${l.k.split(' ')[0]}</span></div>`).join('')}
function renderChecklist(){const extra={ 'Violência doméstica':['Verificar medida protetiva','Avaliar risco atual da vítima','Separar partes e ouvir vítima com segurança','Encaminhar vítima a atendimento se necessário'], 'Tráfico de drogas':['Descrever fracionamento/quantidade','Relacionar dinheiro, balança, celular e demais indícios','Acondicionar substância','Conduzir para autoridade policial'], 'Embriaguez ao volante':['Registrar sinais de alteração psicomotora','Oferecer teste se disponível','Auto de constatação/recusa','Providências de trânsito e veículo'], 'Barreira policial':['Sinalização e segurança da via','Posicionamento das viaturas','Critério de seleção dos veículos','Comunicação à SOp']}; const arr=[...checklistBase,...(extra[$('checkType').value]||[])]; $('checkList').innerHTML=arr.map(x=>`<label class="checkrow"><input type="checkbox"><span>${x}</span></label>`).join('')}
function saveHist(tipo,txt){const arr=JSON.parse(localStorage.hist||'[]'); arr.unshift({tipo,txt,dt:new Date().toLocaleString('pt-BR')}); localStorage.hist=JSON.stringify(arr.slice(0,100)); renderSalvos()}
function renderSalvos(){const arr=JSON.parse(localStorage.hist||'[]'); $('savedList').innerHTML=arr.length?arr.map((h,i)=>`<div class="item"><b>${h.tipo}</b><span class="muted">${h.dt}</span><p class="muted">${h.txt.slice(0,180)}...</p><button class="btn light" onclick="navigator.clipboard.writeText(JSON.parse(localStorage.hist)[${i}].txt)">Copiar</button></div>`).join(''):'<p class="muted">Nenhum histórico salvo.</p>'}
function copyText(id){navigator.clipboard.writeText($(id).textContent); alert('Copiado.')}
function exportSalvos(){const arr=JSON.parse(localStorage.hist||'[]'); const blob=new Blob([arr.map(h=>`--- ${h.dt} | ${h.tipo} ---\n${h.txt}`).join('\n\n')],{type:'text/plain'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='historicos-salvos.txt'; a.click()}
init();
